name: Push-to-AWS-EC2-Server

on: 
  push:
    branches:    
      - main 

jobs:
  deploy:
    name: Push to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: npm install
        run: |
          npm install

      - name: npm build
        run: |
          npm run build

      # - name: Configure env
      #   run: |
      #     cat > .env << EOF
      #     ${{ secrets.ENVIRONMENT }}
      #     EOF

      - name: Deploy to my EC2 instance
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          SOURCE: "public/"
          REMOTE_HOST: "ec2-13-51-252-66.eu-north-1.compute.amazonaws.com"
          REMOTE_USER: "ubuntu"
          TARGET: "/home/ubuntu/backend/public"