name: 🚀 Deploy File to cPanel
on: 
  push:
    branches:    
      - main 
jobs:
  FTP-Deploy-Action:
    name: 🎉 Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v1
      
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16
    
      - name: npm install
        run: |
          npm install --force

      - name: npm build
        run: |
          npm run build
          
      - name: 📂 Sync folders and files to the server
        uses: SamKirkland/FTP-Deploy-Action@4.3.3
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./build/
          server-dir: ./public/